name: DownloadSecureFile

on:
  workflow_call:

jobs:
  download_secure_file:
    runs-on: ubuntu-latest
    steps:
     - name: Download_Secrets
       id: Download_Secrets
       run: | 
          echo "This is Call Test : ${{ secrets.CALL_TEST }} and This is Test : ${{ secrets.TEST }} > main.txt
          cat main.txt