name: DownloadSecureFile

on:
  workflow_call:
    secrets:
      CALL_TEST:
        required: true
jobs:
  download_secure_file:
    runs-on: ubuntu-latest
    steps:
     - name: Download_Secrets
       id: Download_Secrets
       run: echo "${{ secrets.CALL_TEST }}"